CREATE TABLE [dbo].[User]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Role INT NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	FirstName NVARCHAR(50) NULL,
	LastName NVARCHAR(50) NULL,
	Password NVARCHAR(50) NOT NULL
)
